pos-django-main/pos/urls.py
from django.urls import path
from pos import views

app_name = 'pos'

urlpatterns = [
    path('', views.home, name='home'),
    path('new-order/', views.buat_order, name='buat-order'),
    path('daftar-menu/<int:order_id>/', views.daftar_menu, name='daftar-menu'),
    path('tambah-item/<int:order_id>/<int:menu_id>/', views.tambah_item, name='tambah-item'),
    path('order-aktif/', views.order_aktif, name='order-aktif'),
    path('print-order/<int:id>/', views.print_order, name='print-order'),
    path('batal-order/<int:id>/', views.batal_order, name='batal-order'),
    path('bayar-order/<int:id>/', views.bayar_order, name='bayar-order'),
]

pos-django-main/pos_caffe_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pos.urls', namespace='pos')),
]

pos-django-main/pos/models.py
from django.db import models

"""
Migrations for 'pos':
  pos/migrations/0001_initial.py
    - Create model Menu
    - Create model Order
    - Create model Item
"""


class Menu(models.Model):
    nama = models.CharField(max_length=100)
    price = models.PositiveIntegerField(default=10000)
    image = models.URLField()
    
    def __str__(self):
        return self.nama
    

class Order(models.Model):
    meja = models.CharField(max_length=100)
    pelanggan = models.CharField(max_length=100)
    total = models.PositiveIntegerField(default=0)
    dibayar = models.PositiveIntegerField(default=0)
    kembali = models.PositiveIntegerField(default=0)
    selesai = models.BooleanField(default=False)

    def __str__(self):
        return self.meja

    
class Item(models.Model):
    order = models.ForeignKey(Order,
                              related_name='order_item', 
                              on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu, 
                             related_name='menu_item', 
                             on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    harga = models.PositiveIntegerField(default=0)
    subtotal = models.PositiveIntegerField(default=0)
    catatan = models.CharField(max_length=200, blank=True, null=True)
    dikirim = models.BooleanField(default=False)
    
    def __str__(self):
        return self.menu.nama
    

    
    

pos-django-main/pos/forms.py
from django import forms

from pos.models import Order


class BuatOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'meja',
            'pelanggan',
        ]


class BayarOrderForm(forms.Form):
    dibayar = forms.IntegerField()

pos-django-main/pos/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ValidationError

from pos.forms import BuatOrderForm, BayarOrderForm
from pos.models import Menu, Order, Item


def home(request):
    return render(request, 'pos/home.html')


def daftar_menu(request, order_id):
    menu_list = Menu.objects.all()
    order = get_object_or_404(Order, pk=order_id)

    page = request.GET.get('page', 1)
    
    paginator = Paginator(menu_list, 10)
    
    try:
        menus = paginator.page(page)
    except PageNotAnInteger:
        menus = paginator.page(1)
    except EmptyPage:
        menus = paginator.page(paginator.num_pages)
    
    return render(request, 
                  'pos/daftar_menu.html', 
                  {'menus': menus,
                   'order': order})
    

def buat_order(request):
    if request.method == 'POST':
        form = BuatOrderForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.total = 0
            obj.dibayar = 0
            obj.kembali = 0
            obj.save()
            return redirect('pos:daftar-menu', order_id=obj.pk)

    else:
        form = BuatOrderForm()
    return render(request, 'pos/buat_order.html', {'form': form})


def order_aktif(request):
    order_list = Order.objects.filter(selesai=False)
    page = request.GET.get('page', 1)
    paginator = Paginator(order_list, 10)

    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)

    return render(request,
                  'pos/order_aktif.html',
                  {'orders': orders})


def tambah_item(request, order_id, menu_id):
    order = get_object_or_404(Order, id=order_id)
    menu = get_object_or_404(Menu, id=menu_id)
    item, created = Item.objects.get_or_create(
        menu=menu,
        order=order
    )

    item.qty = item.qty + 1
    item.harga = menu.price
    item.subtotal = item.harga * item.qty
    item.save()

    items = Item.objects.filter(order=order).aggregate(total=Sum('subtotal'))
    order.total = items['total']
    order.save()

    return redirect('pos:daftar-menu', order_id=order.id)


def batal_order(request, id):
    order = get_object_or_404(Order, id=id)
    order.delete()
    return redirect('pos:order-aktif')


def bayar_order(request, id):
    order = get_object_or_404(Order, id=id, selesai=False)

    if request.method == 'POST':
        form = BayarOrderForm(data=request.POST)

        if form.is_valid():
            dibayar = form.cleaned_data['dibayar']

            if dibayar < order.total:
                raise ValidationError('Uang Anda kurang!')

            order.kembali = dibayar - order.total
            order.dibayar = dibayar
            order.selesai = True
            order.save()

            return render(
                request,
                'pos/print_order.html',
                {'order': order}
            )

    else:
        form = BayarOrderForm()

    return render(request,
                  'pos/bayar_order.html',
                  {'order': order, 'form': form})


def print_order(request, id):
    order = get_object_or_404(Order, id=id)
    return render(request, 'pos/print_order.html', {'order': order})



def buat_item(request):
    pass


def ubah_status_item(request):
    pass


def cetak_struk(request):
    pass

pos-django-main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Cabin+Sketch">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body class="bg-dark text-light" style="font-family: 'Cabin Sketch','Times New Roman', Times, serif;">
  {% include "pos/components/navbar.html" %}
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

pos-django-main/templates/pos/bayar_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Bayar Order{% endblock %}


{% block content %}
  <div class="row mt-5 d-flex justify-content-center">
    <div class="col-lg-5 ">

      <div class="card bg-dark shadow">
        <div class="card-body">
          <h2 class="card-title">order รวม {{ order.total }}</h2>
          <p>ลูกค้า {{ order.pelanggan }}</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit"
                    class="btn btn-success btn-lg btn-block"
            >
              Buy
            </button>
          </form>
        </div>
      </div>

    </div>

  </div>
{% endblock %}

pos-django-main/templates/pos/buat_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}New Order{% endblock %}


{% block content %}
  <div class="row mt-5">
    <div class="col-md-12">
      <h1 class="display-2 text-shadow d-flex justify-content-center">
        New Order
      </h1>
      <h4 class="mt-4 d-flex justify-content-center">
        ใส่หมายเลขโต๊ะและชื่อลูกค้า
      </h4>
    </div>
  </div>
  <div class="row mt-3 d-flex justify-content-center">
    <div class="col-lg-5 ">

      <div class="card bg-dark">
        <div class="card-body">
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit"
                    class="btn btn-success btn-lg btn-block"
            >
              Simpan
            </button>
          </form>
        </div>
      </div>

    </div>

  </div>
{% endblock %}

pos-django-main/templates/pos/components/navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Cafe project</a>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'pos:buat-order' %}">New Order</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'pos:order-aktif' %}">Order</a>
      </li>
    </ul>
  </div>
</nav>

pos-django-main/templates/pos/components/order_info.html
<div class="card bg-warning text-dark border-dark shadow-lg">
  <div class="card-body">
    <h1 class="card-title">Meja {{ order.meja }}</h1>
    <h3>IDR {{ order.total }}, A/N {{ order.pelanggan }}</h3>
  </div>

  <ul class="list-group list-group-flush bg-warning">
    {% for item in order.order_item.all %}
      <li class="list-group-item text-dark bg-warning">
        {{ item.menu.nama }} <br>
        IDR {{ item.harga }} x {{ item.qty }} = IDR {{ item.subtotal }}
      </li>
    {% empty %}
      <li class="list-group-item text-dark bg-warning">
        Item belum ada!
      </li>
    {% endfor %}
  </ul>

  <div class="card-footer">
    <a href="#" class="btn btn-success btn-lg btn-block">Bayar</a>
  </div>
</div>

pos-django-main/templates/pos/daftar_menu.html
{% extends "base.html" %}

{% block title %}Daftar Menu{% endblock %}


{% block content %}
  <div class="row mt-5">
    <div class="col-md-12">
      <h1 class="display-2 text-shadow d-flex justify-content-center">
        Daftar Menu
      </h1>
      <h4 class="mt-4 d-flex justify-content-center">
        menu 
      </h4>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-lg-12">
      {% include "pos/components/order_info.html" with order=order %}
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-12">

      <div class="card-columns">
        {% for menu in menus %}
        <div class="card bg-warning text-center text-dark border-dark shadow">
          <img src="{{ menu.image }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h1 class="card-title">{{ menu.nama }}</h1>
            <h3 class="card-text">IDR {{ menu.price }}</h3>
            <a href="{% url 'pos:tambah-item' order_id=order.id menu_id=menu.id %}" class="btn btn-dark btn-block btn-lg">Pesan</a>
          </div>
        </div>
        {% endfor %}
      </div>

    </div>

  </div>
{% endblock %}

pos-django-main/templates/pos/home.html
{% extends "base.html" %}

{% block title %}Simple POS{% endblock %}

{% block content %}
<div class="row mt-5">
  <div class="col-md-12">
    <h1 class=" display-2 d-flex justify-content-center">
     CAFE
    </h1>
    <h4 class=" mt-4 d-flex justify-content-center">
      
      &nbsp;
      <span class="text-success"></span>&nbsp;
      
    </h4>
  </div>
</div>
<div class="row mt-3 d-flex justify-content-center text-light">

  <div class="col-xl-12 mb-4">
    <a href="{% url 'pos:buat-order' %}" class="text-decoration-none">
      <div class="card bg-warning text-dark">
        <div class="card-body shadow d-flex justify-content-center">
          <h4 class="display-2 text-pink card-title text-center">
            New Order
          </h4>
        </div>
      </div>
    </a>
  </div>
  <div class="col-xl-12 mb-4">
    <a href="{% url 'pos:order-aktif' %}" class="text-decoration-none">
      <div class="card bg-warning text-dark">
        <div class="card-body shadow d-flex justify-content-center">
          <h4 class="display-2 card-title text-center">
            Active Order
          </h4>
        </div>
      </div>
    </a>
  </div>
</div>
{% endblock %}

pos-django-main/templates/pos/order_aktif.html
{% extends "base.html" %}

{% block title %}Daftar Menu{% endblock %}


{% block content %}
  <div class="row mt-5">
    <div class="col-md-12">
      <h4 class="display-2 text-center text-shadow ">
        Order
      </h4>
      <h4 class="mt-4 text-center">
        order ที่มีอยู่
      </h4>
    </div>
  </div>
<div class="row mt-3">
  <div class="col-lg-12">

    <div class="card-columns">
      {% for order in orders %}
      <div class="card bg-warning text-dark border-dark shadow-lg">
        <div class="card-body">
          <h1 class="card-title">{{ order.meja }}</h1>
          <h3>IDR {{ order.total }}, A/N {{ order.pelanggan }}</h3>
        </div>
        <ul class="list-group list-group-flush bg-warning">
          {% for item in order.order_item.all %}
            <li class="list-group-item text-dark bg-warning">
              {{ item.menu.nama }} <br>
              IDR {{ item.harga }} x {{ item.qty }} = IDR {{ item.subtotal }}
            </li>
          {% empty %}
            <li class="list-group-item text-dark bg-warning">
              Item
            </li>
          {% endfor %}
        </ul>
        <div class="card-footer">
          <div class="btn-group d-flex justify-content-end" role="group">
            <a href="{% url 'pos:daftar-menu' order_id=order.id %}"
               class="btn btn-dark btn-lg"
            >
              ดูรายการ
            </a>
            <a href="{% url 'pos:bayar-order' id=order.id %}"
               class="btn btn-success btn-lg"
            >
              ขาย
            </a>
            <a href="{% url 'pos:batal-order' id=order.id %}"
               class="btn btn-danger btn-lg"
            >
              ยกเลิก
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

  </div>

</div>
{% endblock %}

pos-django-main/templates/pos/print_order.html
<pre style="width: 300px; margin: 0 auto; padding: 2px;">
  NOMOR MEJA {{ order.meja|upper }}
  ===========================

  PESANAN:
{% for item in order.order_item.all %}
  #{{ forloop.counter }}. {{ item.menu.nama|upper }}
      QTY                 {{ item.qty }}
      HARGA               IDR. {{ item.harga }}
      SUBTOTAL            IDR. {{ item.subtotal }}
{% endfor %}

  TOTAL                  IDR. {{ order.total }}
  CUSTOMER               BPK/IBU. {{ order.pelanggan }}
  PAYMENT                IDR. {{ order.dibayar }}
  CHANGE                 IDR. {{ order.kembali }}
</pre>

<script>
  window.print()
</script>